# syntax=docker/dockerfile:1.7-labs
FROM composer AS require-server

WORKDIR /app

COPY --exclude=vendor --exclude=node_modules . /app/

RUN composer install --ignore-platform-reqs

FROM node:22-slim AS npm

RUN apt-get update && apt-get -y install ca-certificates && \
    sed -i.bak -r 's@http://deb\.debian\.org/?@https://ftp.riken.jp/Linux/debian/@g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update
RUN apt-get update && apt-get install php -y

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV CI=true
RUN corepack enable

COPY --from=require-server --exclude=public/build /app /app
WORKDIR /app
RUN pnpm install --frozen-lockfile && pnpm run build

FROM nginx

COPY --from=npm /app/public /app/public

COPY nginx.site.conf /etc/nginx/conf.d/default.conf