FROM dunglas/frankenphp:php8.4.17

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
	nodejs \
	npm \
    && npm install -g pnpm@latest-10 \
    && install-php-extensions \
        pcntl \
        mysqli \
        pdo_mysql \
        excimer \
        memcached \
        opcache

COPY --from=composer /usr/bin/composer /usr/bin/composer

#ARG USER=www-data
#RUN adduser -D ${USER}; \
#    setcap -r /usr/local/bin/frankenphp; \
#	chown -R ${USER}:${USER} /config/caddy /data/caddy
#USER ${USER}

CMD ["frankenphp", "run"]
#CMD ["php", "artisan", "octane:frankenphp", "--log-level", "debug"]
