# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "mkaraki"

  - package-ecosystem: "composer"
    directory: "/imageViewer/"
    schedule:
      interval: "monthly"
    assignees:
      - "mkaraki"

  - package-ecosystem: "docker"
    directory: "/imageViewer/"
    schedule:
      interval: "monthly"
    assignees:
      - "mkaraki"

  - package-ecosystem: "docker"
    directory: "/imageEvaller/"
    schedule:
      interval: "monthly"
    assignees:
      - "mkaraki"

  - package-ecosystem: "pip"
    directory: "/imageEvaller/"
    schedule:
      interval: "monthly"
    assignees:
      - "mkaraki"

  - package-ecosystem: "docker"
    directory: "/utils/imageCompress/"
    schedule:
      interval: "monthly"
    assignees:
      - "mkaraki"

  - package-ecosystem: "pip"
    directory: "/uitls/imageCompress/"
    schedule:
      interval: "monthly"
    assignees:
      - "mkaraki"

  - package-ecosystem: "docker"
    directory: "/imageServer/"
    schedule:
      interval: "monthly"
    assignees:
      - "mkaraki"

  - package-ecosystem: "gomod"
    directory: "/imageServer/"
    schedule:
      interval: "monthly"
    assignees:
      - "mkaraki"
