services:
  runner:
    build:
      context: imageEvaller
      dockerfile: Dockerfile.dev
    volumes:
      - ./imageEvaller/src/imageevaller:/usr/src/app/
      - ./imageEvaller/models:/usr/src/app/models:ro
      - ./imageEvaller/images:/usr/src/app/images:ro
    environment:
      - CUDA_VISIBLE_DEVICES=""
    depends_on:
      - db
    profiles:
      - tools

  viewer:
    build:
      context: imageViewer
      dockerfile: Dockerfile.dev
    volumes:
      - ./imageEvaller/images:/usr/src/app/images:ro
      - ./imageViewer:/app
    ports:
      - 7090:8000
    depends_on:
      - db
      - memcached
    entrypoint: php artisan octane:frankenphp --workers=4 --max-requests=1

  img-server:
    build: imageServer
    volumes:
      - ./imageEvaller/images:/usr/src/app/images:ro
    ports:
      - 7092:8080
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - 7091:3306
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=illustStore
      - MARIADB_USER=illustStore
      - MARIADB_PASSWORD=illustStore
    volumes:
      - dbdebug:/var/lib/mysql:Z

  memcached:
    image: memcached:1.6-alpine
    command: memcached -m 1024

volumes:
  dbdebug: {}
