services:
  runner:
    build: imageEvaller
    volumes:
      - ./imageEvaller/:/usr/src/app/
      - ./imageEvaller/models:/usr/src/app/models:ro
      - ./imageEvaller/images:/usr/src/app/images:ro
    environment:
      - CUDA_VISIBLE_DEVICES=""
    depends_on:
      - db

  compressor:
    build: utils/imageCompress
    volumes:
      - ./utils/imageCompress:/usr/src/app/
      - ./imageEvaller/images:/usr/src/app/images
    depends_on:
      - db

  viewer:
    build: imageViewer
    volumes:
      - ./imageEvaller/images:/usr/src/app/images:ro
      - ./imageViewer:/var/www/html
    ports:
      - 7090:80
    depends_on:
      - db

  img-server:
    build: imageServer
    volumes:
      - ./imageEvaller/images:/usr/src/app/images:ro
    ports:
      - 7092:8080
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - 7091:3306
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=illustStore
      - MARIADB_USER=illustStore
      - MARIADB_PASSWORD=illustStore
    volumes:
      - ./dbdebug:/var/lib/mysql:Z
      - ./init.db:/docker-entrypoint-initdb.d:ro
