version: "3.7"

services:
  runner:
    build: .
    volumes:
      - ./models:/usr/src/app/models:ro
      - ./images:/usr/src/app/images:ro
    environment:
      - CUDA_VISIBLE_DEVICES=""
  db:
    image: mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=illustStore
      - MARIADB_USER=illustStore
      - MARIADB_PASSWORD=illustStore
    volumes:
      - ./dbdebug:/var/lib/mysql:Z
      - ../init.db:/docker-entrypoint-initdb.d:ro