[project]
name = "imageEvaller"
version = "0.1.0"
# https://www.tensorflow.org/install/pip#software_requirements
# Uses 3.11 as minimum version because mysql-connector-python does not support Python 3.9 and CVE of Keras library
requires-python = ">=3.11,<3.13"
dependencies = [
    "deepdanbooru==1.0.4",
    "tensorflow==2.20.0",
    "tensorflow-io==0.37.1",
    "mysql-connector-python==9.5.0",
    "ImageHash==4.3.2",
    "sentry-sdk==2.53.0",
    "lepton-jpeg-python==0.5.8",
]

[project.scripts]
imageevaller = "imageevaller:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.11.0"]
build-backend = "uv_build"
