FROM rust:1-alpine as build

WORKDIR /app
COPY Cargo.toml Cargo.lock /app/
COPY src /app/src

RUN cargo build --locked --release --target=x86_64-unknown-linux-musl

CMD ["/app/target/x86_64-unknown-linux-musl/release/imageServer"]
