name: evaller test
permissions:
  contents: read

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to DHI
        run: echo "$DOCKER_PAT" | sudo docker login dhi.io -u "$DOCKER_USER" --password-stdin
        env:
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}

      - name: Install required package
        run: sudo apt-get update && sudo apt-get install -y unzip imagemagick

      - name: Prepare model
        run: |
          wget -O deepdanbooru.zip https://github.com/KichangKim/DeepDanbooru/releases/download/v3-20211112-sgd-e28/deepdanbooru-v3-20211112-sgd-e28.zip
          unzip deepdanbooru.zip
          mkdir -p imageEvaller/models/deepdanbooru
          mv model-resnet_custom_v3.h5 imageEvaller/models/deepdanbooru/model.h5
          mv tags.txt imageEvaller/models/deepdanbooru/tags.txt

      - name: Prepare image
        run: |
          mkdir -p imageEvaller/images
          convert -size 720x1280 canvas:white imageEvaller/images/white.png
          convert -size 1280x720 canvas:black imageEvaller/images/black.png
          convert -size 1280x720 xc: +noise Random -virtual-pixel tile -blur 0x1 -resize 1280x720 imageEvaller/images/random.png
          convert -size 500x500 gradient: -evaluate Pow 0.5 imageEvaller/images/gradient.png

      - name: Build docker
        run: sudo docker compose -f docker-compose.dev.yaml build runner

      - name: Run mariadb
        run: |
          sudo docker compose -f docker-compose.dev.yaml up -d --wait db
          sleep 60

      - name: Run test
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN_EVALLER }}
        run: sudo docker compose -f docker-compose.dev.yaml run -e SENTRY_ENVIRONMENT=e2e-test -e SENTRY_DSN_URL=$SENTRY_DSN --rm runner --verbose

      - name: Show result
        run: |
          echo "SELECT * FROM illusts;" > test.sql
          echo "SELECT * FROM tagAssign;" >> test.sql
          sudo docker compose -f docker-compose.dev.yaml exec db mariadb illustStore < test.sql

      - name: Stop mariadb
        run: sudo docker compose -f docker-compose.dev.yaml down db
